title: Operating Systems
revision: DEMO 001 09-Aug-2021
footer:
  copyright: © 2021

description: >-
  This is the CSF-265 Operating System course site,
  a GitHub Page, hosted at GitHub.com (thank you!).
  It contains links to lecture materials, exam questions, and laboratory materials.
  It is based on "Google Here, Google There, Try This, Try That, and then Ask Anybody (GHGTT4A2)".
  This site is managed by VauLSMorg ([vlsm.org](http://vlsm.org/)) since 2018.
disclaimer: >-
  You are free to share, copy and redistribute the material of this site 
  in any medium or format for any purpose, even commercially. 
  Please give appropriate credit, provide a link to the page, 
  and indicate if changes were made. You may do so in any reasonable manner. 
  You should not apply legal terms or technological measures, 
  that legally restrict others from doing anything that is permitted here.

# Author information
author:
  name: "Operating Systems"
  address: "Local Host"

# Google Analytics
google_analytics: ""

# Build settings
plugins:
  - "jekyll-github-metadata"

urlweb:           "https://os.vlsm.org/"
urlscele:         "https://scele.cs.ui.ac.id/course/view.php?id=3134"
urllogcode:       "https://osp4diss.vlsm.org/ETC/logCodes.txt"
urlcontact:       "TBA"
urlgithub:        "https://github.com/UI-FASILKOM-OS/SistemOperasi"
urlghpage:        "https://os.vlsm.org/"

# Logo configuration (for navbar). Alt text will be used if failed
logo: /favicon.ico
alt_text: Mr. Yoda Yoda

# Internal links configuration (for navbar)
# This is ONLY USED for links inside the site since it will be plugged into site's URL
# URL should be formed in /<directory> format (/ = project root directory)
internal_links:
  # Example format:
  # - <newline>
  #   name: "Example Internal Links"
  #   url: "/Gemfile"
  -
    name: Home
    url: "/"
  - 
    name: Listings
    url: "/000.html"
  -
    name: GitHubPages
    url: "/GitHubPages/"
  -
    name: Report
    url: "/REPORT/"

# External links configuration (for navbar)
# This is ONLY USED for links OUTSIDE the site or formed as absolute URLs
external_links:
  # Example format:
  # - <newline>
  #   name: "Example External Links"
  #   url: "https://www.google.com"
  -
    name: LOG CODES
    url: "https://osp4diss.vlsm.org/ETC/logCodes.txt"
  - 
    name: SCELE
    url: "https://scele.cs.ui.ac.id/course/view.php?id=3134"
  -
    name: GitHub
    url: "https://github.com/OSP4DISS/SistemOperasiDev/"
  - 
    name: OS.vlsm.org
    url: "https://osp4diss.github.io/SistemOperasiDev/"

keywords:         "jekyll, testing"
github:           [metadata]

layout: default
